hoflaeden_suchen:
  fields:
    suchbegriff:
      example: "Käse"
      selector:
        text:
    kategorie:
      example: "Gemüse"
      selector:
        text:
    produkt:
      example: "Kartoffeln"
      selector:
        text:
    verkaufsart:
      example: "Ab-Hof-Verkauf"
      selector:
        text:
    zahlungsart:
      example: "TWINT"
      selector:
        text:
    merkmal:
      example: "Bio"
      selector:
        text:
    nur_geoeffnet:
      example: true
      selector:
        boolean:
